# Generated by Django 2.0.5 on 2018-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('pass_word', models.CharField(max_length=64)),
                ('user_token', models.CharField(max_length=64)),
                ('token_last_modified', models.DateTimeField()),
            ],
        ),
    ]
